language: python 
os: linux
python:
  - "3.7"
  - "3.8"
 
before_install:
    - travis_wait mvn 30 install
install: pip install -r beamshapes/tests/requirements_test.txt
    

branches:
  only:
    - dev
script: python -m unittest discover beamshapes/tests

