language: python 
os: linux
python:
  - "3.7"
  - "3.8"
 
install:
    - pip install -r beamshapes/tests/requirements_test.txt
    - travis_wait mvn install

branches:
  only:
    - dev
script: python -m unittest discover beamshapes/tests

